Fix parse error for "user" field from API
Fixes this error in the tests:
  thread 'json' (2221064) panicked at tests/lib.rs:26:73:
  called `Result::unwrap()` on an `Err` value: Error("relative URL without a base: \"(multiple)\"", line: 1623, column: 40)

due to the "user" field not always containing a valid URL